'use client';
import { useEffect, useRef, useState, type CSSProperties, type PointerEvent } from 'react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Flame, Utensils, MapPin, Clock, Phone, Menu, X, Pause, Play, Plus } from 'lucide-react';

const categories = ['Mandi', 'From the grill', 'For the table', 'Something sweet'];
const dishes = [
 {name:'Classic chicken mandi',category:'Mandi',detail:'Tender roasted chicken, aromatic long-grain rice, and a little smoky magic.',tag:'THE ORIGINAL',image:true},
 {name:'Slow-cooked mutton mandi',category:'Mandi',detail:'A generous, slow-cooked centrepiece made for unhurried meals.',tag:'WORTH THE WAIT'},
 {name:'Al fahm mandi',category:'Mandi',detail:'Charcoal-grilled chicken meets fragrant mandi rice.',tag:'SMOKE & SPICE'},
 {name:'Classic al fahm',category:'From the grill',detail:'Flame-kissed chicken with a deeply spiced marinade.',tag:'OVER THE COALS'},
 {name:'Green chilli al fahm',category:'From the grill',detail:'A bright, herby take with a little extra heat.',tag:'TURN UP THE HEAT'},
 {name:'The sharing platter',category:'For the table',detail:'A generous mandi spread for your favourite people.',tag:'BETTER TOGETHER',image:true},
 {name:'Mandi rice & dips',category:'For the table',detail:'Fragrant rice with a selection of accompanying dips.',tag:'THE PERFECT SIDE'},
 {name:'Kunafa',category:'Something sweet',detail:'Golden pastry, soft cheese, and a sweet finish to your feast.',tag:'ONE MORE BITE'},
 {name:'Fresh lime cooler',category:'Something sweet',detail:'A cool, citrusy companion to a smoky feast.',tag:'KEEP IT FRESH'},
];
type Dish = typeof dishes[number];
function BrandLogo({full=false}: {full?:boolean}) {
 return <span className={`brand-logo-tile ${full?'brand-logo-full':'brand-logo-symbol'}`}><img src={full?'/brand/zufra-rust-full.png':'/brand/zufra-symbol-rust.png'} alt="Zufra Mandi" width={full?1775:2312} height={full?3089:3437}/></span>;
}
function FoodPhoto({className='', priority=false}: {className?:string; priority?:boolean}) {
 return <div className={`food-photo-crop ${className}`}><img src="/zufra-chicken-mandi.jpeg" alt="Zufra chicken mandi with fragrant rice and fresh vegetables on a gold platter" width="1086" height="1448" loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'}/></div>;
}
function StarAsset({className=''}: {className?:string}) {
 return <img className={`star-asset ${className}`} src="/brand/star.svg" alt="" aria-hidden="true" width="64" height="64"/>;
}
function tilt(event: PointerEvent<HTMLElement>) {
 if (event.pointerType !== 'mouse' || matchMedia('(prefers-reduced-motion: reduce)').matches || event.currentTarget.closest('.motion-paused')) return;
 const el=event.currentTarget; const box=el.getBoundingClientRect();
 const x=(event.clientX-box.left)/box.width; const y=(event.clientY-box.top)/box.height;
 el.style.setProperty('--tilt-x', `${(0.5-y)*12}deg`);el.style.setProperty('--tilt-y', `${(x-0.5)*16}deg`);
 el.style.setProperty('--light-x',`${x*100}%`);el.style.setProperty('--light-y',`${y*100}%`);
}
function resetTilt(event: PointerEvent<HTMLElement>) {
 event.currentTarget.style.setProperty('--tilt-x','0deg');event.currentTarget.style.setProperty('--tilt-y','0deg');
}
export default function Home() {
 const [mobile,setMobile]=useState(false); const [paused,setPaused]=useState(false); const [selected,setSelected]=useState<Dish|null>(null); const [active,setActive]=useState('home'); const [progress,setProgress]=useState(0); const platter=useRef<HTMLDivElement>(null); const scene=useRef<HTMLElement>(null); const goldMark=useRef<HTMLDivElement>(null);
 useEffect(()=>{ const media=matchMedia('(prefers-reduced-motion: reduce)');setPaused(media.matches);const listener=()=>setPaused(media.matches);media.addEventListener('change',listener);return()=>media.removeEventListener('change',listener)},[]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));const sections=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)}),{rootMargin:'-20% 0px -55% 0px'});document.querySelectorAll('section[id]').forEach(e=>sections.observe(e));let frame=0;const scroll=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{setProgress(scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight));if(platter.current)platter.current.style.setProperty('--scroll-turn',`${paused?0:scrollY*.055}deg`);
 if(scene.current){const box=scene.current.getBoundingClientRect();const p=Math.max(0,Math.min(1,(innerHeight-box.top)/(innerHeight+box.height)));scene.current.style.setProperty('--scene-turn',`${paused?0:(p-.5)*65}deg`);scene.current.style.setProperty('--scene-lift',`${paused?0:(p-.5)*-140}px`);}
 if(goldMark.current){const box=goldMark.current.getBoundingClientRect();const p=(innerHeight/2-box.top)/innerHeight;goldMark.current.style.setProperty('--mark-turn',`${paused?-18:Math.max(-35,Math.min(35,p*45-20))}deg`);}
})};window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',scroll);scroll();return()=>{observer.disconnect();sections.disconnect();window.removeEventListener('scroll',scroll);window.removeEventListener('resize',scroll);cancelAnimationFrame(frame)}},[paused]);
 return <main className={paused?'motion-paused':'motion-active'}>
 <a className="skip-link" href="#menu">Skip to menu</a><div className="scroll-progress" style={{transform:`scaleX(${progress})`}}/>
 <header className="header"><a className="brand" href="#home" aria-label="Zufra Mandi home"><BrandLogo/></a><nav aria-label="Main navigation">{[['story','Our story'],['menu','The menu'],['experience','The experience'],['visit','Find us']].map(([id,label])=><a key={id} href={`#${id}`} className={active===id?'active':''}>{label}</a>)}</nav><a className="button small header-cta" href="#menu">Explore the menu</a><button className="menu-toggle" aria-label={mobile?'Close navigation':'Open navigation'} aria-expanded={mobile} aria-controls="mobile-nav" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
 {mobile&&<nav className="mobile-nav" id="mobile-nav" aria-label="Mobile navigation">{[['home','Home'],['story','Our story'],['menu','The menu'],['experience','The experience'],['visit','Find us']].map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMobile(false)}>{label}</a>)}</nav>}
 <section className="hero" id="home"><div className="embers" aria-hidden="true">{Array.from({length:16},(_,i)=><i key={i} style={{left:`${(i*17+7)%100}%`,top:`${(i*23+13)%100}%`,animationDelay:`${-i*.9}s`}}/>)}</div><div className="hero-copy"><p className="eyebrow">A LITTLE ARABIA. A LOT OF SOUL.</p><h1><span className="headline-line"><span>Good things</span></span><span className="headline-line"><span>come to</span></span><span className="headline-line"><em>those who feast.</em></span></h1><p className="intro">Smoky, slow-cooked mandi. Fragrant rice.<br/>A table that always has room for one more.</p><a className="button" href="#menu">Find your feast</a><a className="text-link" href="#story">The Zufra story</a></div><div className="hero-art" ref={platter} onPointerMove={tilt} onPointerLeave={resetTilt}><div className="hero-halo" aria-hidden="true"/><div className="orbit" aria-hidden="true"/><div className="orbit orbit-two" aria-hidden="true"/><span className="hero-background-word" aria-hidden="true">FEAST</span><span className="art-caption">SLOW COOKED. SOUL SATISFYING.</span><div className="platter-depth"><div className="platter-scroll"><FoodPhoto className="platter" priority/></div></div><div className="seal"><span>MADE FOR</span><strong>sharing</strong><span>THE ZUFRA WAY</span></div></div><div className="hero-bottom"><span>ROOTED IN TRADITION. SHARED WITH LOVE.</span><a href="#story">SCROLL TO SAVOUR ↓</a><button className="hero-motion" onClick={()=>setPaused(!paused)} aria-label={paused?'Enable animations':'Pause animations'}>{paused?<Play size={13}/>:<Pause size={13}/>}<span>{paused?'MOTION OFF':'MOTION ON'}</span></button></div></section>
 <div className="marquee" aria-label="Slow cooked, soul satisfying, always shared"><div aria-hidden="true">{[0,1,2,3].map(i=><span key={i}>SLOW COOKED <StarAsset/> SOUL SATISFYING <StarAsset/> ALWAYS SHARED <StarAsset/> </span>)}</div></div>
 <section id="story" className="section story"><div className="story-side reveal"><span className="section-number">01 / OUR STORY</span><div className="gold-stage" ref={goldMark} aria-hidden="true"><div className="gold-aura"/><div className="supplied-logo-stage"><img src="/brand/zufra-rust-full.png" alt="" width="1775" height="3089"/></div><StarAsset className="gold-spark spark-one"/><StarAsset className="gold-spark spark-two"/></div><span className="fine">GOOD FOOD IS A LANGUAGE WE ALL SPEAK.</span></div><div className="reveal"><p className="eyebrow">THE ZUFRA FEELING</p><h2>One table.<br/><em>A thousand<br/>conversations.</em></h2><p className="story-text">Some meals fill a plate. The best ones bring people together. That’s the feeling at the heart of Zufra: a generous feast, familiar faces, and no reason to rush.</p><p className="placeholder-note">Our story is still being written. Restaurant history and kitchen details coming soon.</p><a className="text-link" href="#experience">Come a little closer</a></div></section>
 <section id="menu" className="section menu-section"><div className="section-heading reveal"><div><p className="eyebrow">FOLLOW YOUR CRAVINGS</p><h2>Big flavour.<br/><em>Bigger appetites.</em></h2></div><p>A little smoke. A little spice. A lot to share.<br/><span className="placeholder-note">Sample menu · dishes and prices to be confirmed.</span></p></div><Tabs defaultValue="Mandi"><TabsList className="menu-tabs" aria-label="Menu categories">{categories.map(c=><TabsTrigger key={c} value={c}>{c}</TabsTrigger>)}</TabsList>{categories.map(c=><TabsContent key={c} value={c}><div className="dish-grid">{dishes.filter(d=>d.category===c).map((d,i)=><button className={`dish-card ${d.image?'featured-dish':''}`} key={d.name} style={{'--card-index':i} as CSSProperties} onPointerMove={tilt} onPointerLeave={resetTilt} onClick={()=>setSelected(d)} aria-label={`View ${d.name} details`}>{d.image?<div className="dish-image"><FoodPhoto/></div>:<div className="dish-placeholder"><Utensils size={30}/><span>Dish photo coming soon</span><span className="dish-index">0{i+1}</span></div>}<div className="dish-content"><span className="dish-tag">{d.tag}</span><h3>{d.name}</h3><p>{d.detail}</p><div className="dish-footer"><span>Price coming soon</span><Plus size={19}/></div></div></button>)}</div></TabsContent>)}</Tabs><p className="menu-disclaimer">All dishes are illustrative placeholders. Final ingredients, portions, prices, and allergen information will be added to the confirmed menu.</p></section>
 <section className="feast-scene" ref={scene} aria-label="A feast made to share"><div className="feast-scene-sticky"><div className="scene-orbit" aria-hidden="true"/><p className="eyebrow">SOME THINGS DESERVE YOUR FULL ATTENTION</p><h2 className="scene-heading"><span>Less scrolling.</span><em>More savouring.</em></h2><div className="scene-platter"><FoodPhoto/></div><div className="scene-caption"><span>A FEAST MADE TO SHARE</span><span>THE ZUFRA WAY</span></div></div></section>
 <section id="experience" className="experience"><div className="experience-inner"><p className="eyebrow reveal">THE FEAST IS ONLY HALF THE STORY</p><h2 className="reveal">Put the phone down.<br/><em>Pass the platter.</em></h2><p className="reveal">The best seat in the house is the one surrounded by your people.</p><div className="rituals"><article className="reveal"><Flame/><span>01</span><h3>Feel the warmth</h3><p>Smoky flavours. Comforting aromas. The anticipation of that first bite.</p></article><article className="reveal"><Utensils/><span>02</span><h3>Make room for more</h3><p>A feast is better with company. Bring your people and your appetite.</p></article><article className="reveal"><StarAsset className="ritual-star"/><span>03</span><h3>Stay a little longer</h3><p>Let the conversation flow. Some moments deserve to be savoured.</p></article></div></div><span className="experience-word" aria-hidden="true">TOGETHER</span></section>
 <section className="section visit" id="visit"><div className="reveal"><p className="eyebrow">THERE’S A PLACE FOR YOU HERE</p><h2>Your next<br/><em>favourite table.</em></h2><p>We’re getting the details ready.<br/>Everything you need to visit will be right here.</p><div className="contact-row"><MapPin/><div><h3>Find Zufra</h3><p>[Restaurant address & city]</p></div></div><div className="contact-row"><Clock/><div><h3>Come hungry</h3><p>[Opening days & hours]</p></div></div><div className="contact-row"><Phone/><div><h3>Let’s talk</h3><p>[Phone number & WhatsApp]</p></div></div></div><div className="visit-card reveal"><span className="section-number">YOUR TABLE, SOON.</span><div className="visit-mark supplied-visit-logo"><img src="/brand/zufra-sand-full.png" alt="Zufra Mandi logo" width="1775" height="3089"/></div><p>Good food.<br/>Even better company.</p><div className="visit-status"><MapPin size={18}/><span>Location to be announced</span></div><small>Map, directions, ordering, and reservations will be available once restaurant details are confirmed.</small></div></section>
 <section className="faq section"><p className="eyebrow">A FEW THINGS TO KNOW</p><div>{[['Is this the final menu?','Not yet. These are sample dishes to show the menu layout. The confirmed menu, portions, prices, and food photography will be added here.'],['Can I order or reserve a table?','Online ordering and reservations are not connected yet. Contact and booking options will appear once the restaurant details are confirmed.'],['Where is Zufra Mandi located?','The restaurant address, opening hours, and map are placeholders for now. Check the visit section for updates.'],['What about dietary needs and allergens?','The final menu will include confirmed dietary and allergen information. Please check with the restaurant before ordering once contact details are available.']].map(([q,a])=><details key={q}><summary>{q}<Plus size={19}/></summary><p>{a}</p></details>)}</div></section>
 <footer><div className="footer-wordmark"><div className="footer-full-logo"><img src="/brand/zufra-sand-full.png" alt="Zufra Mandi" width="1775" height="3089"/></div><StarAsset/></div><div className="footer-top"><a className="brand" href="#home" aria-label="Zufra Mandi home"><BrandLogo full/></a><p>Come hungry. Leave happy.</p><a className="text-link" href="#home">Back to top ↑</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Zufra Mandi.</span><span>Restaurant details & menu are placeholders.</span><button className="motion-control" onClick={()=>setPaused(!paused)}>{paused?<Play size={14}/>:<Pause size={14}/>} {paused?'Enable motion':'Pause motion'}</button></div></footer>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="dish-dialog"><span className="eyebrow">A TASTE OF WHAT’S TO COME</span><DialogTitle className="dialog-title">{selected?.name}</DialogTitle><DialogDescription className="dialog-description">{selected?.detail}</DialogDescription><div className="dialog-note"><strong>Sample dish · not available to order</strong><p>Price, portion sizes, ingredients, and allergen information are awaiting confirmation.</p></div><a className="button" href="#visit" onClick={()=>setSelected(null)}>View restaurant details</a></DialogContent></Dialog>
 </main>;
}
